# Generated by Django 2.2 on 2019-05-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapi', '0004_auto_20190508_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='isOrder',
            field=models.BooleanField(default=False),
        ),
    ]
