# Generated by Django 2.2.1 on 2019-05-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapi', '0005_transactions_isorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
