# Generated by Django 2.2.1 on 2019-05-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapi', '0007_auto_20190509_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='amount',
        ),
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
