# Generated by Django 2.2.1 on 2019-05-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapi', '0008_auto_20190511_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='items',
            field=models.ManyToManyField(null=True, to='shopapi.Product'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='items',
            field=models.ManyToManyField(null=True, to='shopapi.Product'),
        ),
    ]
