# Generated by Django 2.2 on 2019-05-13 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shopapi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=20)),
                ('categoryDescription', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityName', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryName', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('methodDescription', models.CharField(max_length=20)),
                ('avgDeliveryDays', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'DeilveryMethod',
                'verbose_name_plural': 'Methods',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.DateTimeField(auto_now=True)),
                ('shipDate', models.DateTimeField(default=shopapi.models.default_time)),
                ('arriveDate', models.DateTimeField(default=shopapi.models.arrivedate)),
                ('isOrder', models.BooleanField(default=False)),
                ('deliveryMethod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopapi.DeliveryMethod')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField()),
                ('isOrder', models.BooleanField(default=False)),
                ('orderId', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopapi.Orders')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supName', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('phoneNum', models.IntegerField()),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopapi.City')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=20)),
                ('itemDescription', models.CharField(max_length=200)),
                ('buyingPrice', models.IntegerField()),
                ('sellingPrice', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapi.Categories')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='items',
            field=models.ManyToManyField(to='shopapi.Product'),
        ),
        migrations.AddField(
            model_name='orders',
            name='supId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopapi.Suppliers'),
        ),
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(null=True)),
                ('itemNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapi.Product')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='countryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapi.Country'),
        ),
    ]
