# Generated by Django 2.2.1 on 2019-05-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(default='codefazzer@gmail.com', max_length=250)),
                ('password', models.CharField(default='123456789Bd', max_length=200)),
                ('text', models.CharField(max_length=300)),
                ('dest', models.CharField(max_length=100)),
            ],
        ),
    ]
